### ISSUE TITLE
Incorrect url in your project description, it should be: http://www.freshtariffs.com/

### ISSUE THREAD

**Issue by lingster** [telecomsxchange/freshtariffs#7]
**Describe the bug**
In your project description you have the url as: www.freshtarrifs.com which does not work. http://www.freshtariffs.com/ seems to be the correct url 

**To Reproduce**
Click on the www.freshtarrifs.com link in the project description section. 

**Expected behavior**
It should navigate to: http://www.freshtariffs.com/

**Comment by telecomsxchange** [comment]
Thank you @lingster . it has been fixed.
